# Generated by AddonDevTooling. Do not edit manually.
param(
    [Parameter(Mandatory = $false)]
    [string]$Action = "install",

    [Parameter(Mandatory = $false)]
    [string]$WowPath,

    [Parameter(Mandatory = $false)]
    [string]$Flavor = "retail",

    [Parameter(Mandatory = $false)]
    [switch]$PauseOnExit
)

$modulePath = Join-Path $PSScriptRoot "scripts\AddonDevTools.psm1"
if (-not (Test-Path -LiteralPath $modulePath -PathType Leaf)) {
    throw "AddonDevTools module was not found at '$modulePath'."
}

Import-Module $modulePath -Force

$invokeParams = @{
    RepoRoot        = $PSScriptRoot
    Action          = $Action
    Flavor          = $Flavor
    PauseOnExit     = [bool]$PauseOnExit
    EntryScriptPath = $PSCommandPath
}

if ($PSBoundParameters.ContainsKey("WowPath")) {
    $invokeParams.WowPath = $WowPath
}

Invoke-AddonAction @invokeParams
