# Generated by AddonDevTooling. Do not edit manually.
Set-StrictMode -Version Latest

$script:AddonToolchainVersion = "1.0.0"
$script:GeneratedMarker = "# Generated by AddonDevTooling. Do not edit manually."
$script:GeneratedCmdMarker = ":: Generated by AddonDevTooling. Do not edit manually."
$script:ManifestFileName = "addon-release.json"
$script:DefaultWowPath = "C:\Program Files\Ascension Launcher\resources\client"
$script:DefaultPtrWowPath = "C:\Program Files\Ascension PTR"
$script:SupportedActions = @("install", "link", "clean", "dist", "coverage")
$script:SemVerPattern = '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[A-Za-z-][0-9A-Za-z-]*)(?:\.(?:0|[1-9]\d*|\d*[A-Za-z-][0-9A-Za-z-]*))*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$'

class AddonProject {
    [string]$RepoRoot
    [pscustomobject]$Manifest

    AddonProject([string]$repoRoot, [pscustomobject]$manifest) {
        if ([string]::IsNullOrWhiteSpace($repoRoot)) {
            throw "RepoRoot is required."
        }

        if ($null -eq $manifest) {
            throw "Manifest is required."
        }

        $this.RepoRoot = $repoRoot
        $this.Manifest = $manifest
    }
}

function Get-AddonToolchainInfo {
    [CmdletBinding()]
    param()

    return [pscustomobject]@{
        Version         = $script:AddonToolchainVersion
        GeneratedMarker = $script:GeneratedMarker
        GeneratedCmdMarker = $script:GeneratedCmdMarker
        ManifestFile    = $script:ManifestFileName
    }
}

function Test-AddonSemVer {
    param(
        [Parameter(Mandatory)]
        [string]$Value
    )

    return $Value -match $script:SemVerPattern
}

function Get-NormalizedRepoRoot {
    param(
        [Parameter(Mandatory)]
        [string]$RepoRoot
    )

    if (-not (Test-Path -LiteralPath $RepoRoot)) {
        throw "Repo root was not found at '$RepoRoot'."
    }

    return [System.IO.Path]::GetFullPath((Resolve-Path -LiteralPath $RepoRoot).ProviderPath)
}

function Get-ProjectManifestPath {
    param(
        [Parameter(Mandatory)]
        [string]$RepoRoot
    )

    return Join-Path $RepoRoot $script:ManifestFileName
}

function Resolve-ProjectPath {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project,

        [string]$RelativePath,

        [switch]$AllowEmpty
    )

    if ([string]::IsNullOrWhiteSpace($RelativePath)) {
        if ($AllowEmpty) {
            return $null
        }

        throw "A relative path is required."
    }

    if ([System.IO.Path]::IsPathRooted($RelativePath)) {
        return [System.IO.Path]::GetFullPath($RelativePath)
    }

    return [System.IO.Path]::GetFullPath((Join-Path $Project.RepoRoot $RelativePath))
}

function Get-ProjectStringArray {
    param(
        [Parameter(Mandatory)]
        [object]$Value
    )

    if ($null -eq $Value) {
        return @()
    }

    $result = @($Value | ForEach-Object { [string]$_ })
    return ,$result
}

function Get-OptionalManifestValue {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project,

        [Parameter(Mandatory)]
        [string]$Name
    )

    $property = $Project.Manifest.PSObject.Properties[$Name]
    if ($null -eq $property) {
        return $null
    }

    return $property.Value
}

function Get-ProjectAddonId {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    return [string]$Project.Manifest.addonId
}

function Get-ProjectDisplayName {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    return [string]$Project.Manifest.displayName
}

function Get-ProjectVersion {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    return [string]$Project.Manifest.version
}

function Get-ProjectAddonFolders {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    $result = Get-ProjectStringArray -Value $Project.Manifest.folders
    return ,$result
}

function Get-ProjectAddonFolder {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    $folders = Get-ProjectAddonFolders -Project $Project
    if ($folders.Count -ne 1) {
        throw "Manifest must define exactly one managed folder."
    }

    return [string]$folders[0]
}

function Get-ProjectTocRelativePath {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    return [string]$Project.Manifest.tocPath
}

function Get-ProjectTocPath {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    return Resolve-ProjectPath -Project $Project -RelativePath (Get-ProjectTocRelativePath -Project $Project)
}

function Get-ProjectTocContentRootRelativePath {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    $configured = [string](Get-OptionalManifestValue -Project $Project -Name "tocContentRoot")
    if (-not [string]::IsNullOrWhiteSpace($configured)) {
        return $configured
    }

    $tocRelativePath = Get-ProjectTocRelativePath -Project $Project
    $tocDirectory = Split-Path -Parent $tocRelativePath
    if ([string]::IsNullOrWhiteSpace($tocDirectory)) {
        return "."
    }

    return $tocDirectory
}

function Get-ProjectTocContentRoot {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    return Resolve-ProjectPath -Project $Project -RelativePath (Get-ProjectTocContentRootRelativePath -Project $Project)
}

function Get-ProjectLinkSourceRelativePath {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    $configured = [string](Get-OptionalManifestValue -Project $Project -Name "linkSourcePath")
    if (-not [string]::IsNullOrWhiteSpace($configured)) {
        return $configured
    }

    return Get-ProjectTocContentRootRelativePath -Project $Project
}

function Get-ProjectLinkSourcePath {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    return Resolve-ProjectPath -Project $Project -RelativePath (Get-ProjectLinkSourceRelativePath -Project $Project)
}

function Get-ProjectCoverageScriptPath {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    return Resolve-ProjectPath -Project $Project -RelativePath ([string](Get-OptionalManifestValue -Project $Project -Name "coverageScriptPath")) -AllowEmpty
}

function Get-ProjectCoverageArguments {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    $result = Get-ProjectStringArray -Value (Get-OptionalManifestValue -Project $Project -Name "coverageArguments")
    return ,$result
}

function Get-ProjectVersionFileRelativePath {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    return [string](Get-OptionalManifestValue -Project $Project -Name "versionFilePath")
}

function Get-ProjectVersionFilePath {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    return Resolve-ProjectPath -Project $Project -RelativePath (Get-ProjectVersionFileRelativePath -Project $Project) -AllowEmpty
}

function Get-ProjectDefaultWowPath {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    $configured = [string](Get-OptionalManifestValue -Project $Project -Name "defaultWowPath")
    if ([string]::IsNullOrWhiteSpace($configured)) {
        return $script:DefaultWowPath
    }

    return $configured
}

function Get-ProjectPtrWowPath {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    $configured = [string](Get-OptionalManifestValue -Project $Project -Name "ptrWowPath")
    if ([string]::IsNullOrWhiteSpace($configured)) {
        return $script:DefaultPtrWowPath
    }

    return $configured
}

function Get-ProjectTargetSupport {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    $result = Get-ProjectStringArray -Value $Project.Manifest.targetSupport
    return ,$result
}

function Get-ProjectMinInstallerVersion {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    return [string]$Project.Manifest.minInstallerVersion
}

function Get-ProjectPublishTimeoutSeconds {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    $configured = Get-OptionalManifestValue -Project $Project -Name "publishTimeoutSeconds"
    if ($null -eq $configured) {
        return 120
    }

    return [int]$configured
}

function Get-ProjectReleaseOutputDir {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    $configured = [string](Get-OptionalManifestValue -Project $Project -Name "releaseOutputDir")
    if ([string]::IsNullOrWhiteSpace($configured)) {
        return "release-assets"
    }

    return $configured
}

function Get-ProjectInstallScriptBaseName {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    return "install_{0}" -f (Get-ProjectAddonId -Project $Project)
}

function Get-ProjectGeneratedFileMap {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    $installBaseName = Get-ProjectInstallScriptBaseName -Project $Project

    return [ordered]@{
        ModulePath           = Join-Path $Project.RepoRoot "scripts\AddonDevTools.psm1"
        BuildScriptPath      = Join-Path $Project.RepoRoot "scripts\Build-AscensionRelease.ps1"
        ValidationScriptPath = Join-Path $Project.RepoRoot "scripts\Test-AddonProject.ps1"
        InstallScriptPath    = Join-Path $Project.RepoRoot ("{0}.ps1" -f $installBaseName)
        InstallCmdPath       = Join-Path $Project.RepoRoot ("{0}.cmd" -f $installBaseName)
        LegacyModulePath     = Join-Path $Project.RepoRoot "scripts\AddonDevManager.ps1"
    }
}

function Read-JsonFile {
    param(
        [Parameter(Mandatory)]
        [string]$Path
    )

    return Get-Content -LiteralPath $Path -Raw | ConvertFrom-Json
}

function Write-JsonFile {
    param(
        [Parameter(Mandatory)]
        [string]$Path,

        [Parameter(Mandatory)]
        [object]$Value
    )

    $Value | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $Path -Encoding utf8
}

function Resolve-AddonProject {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$RepoRoot
    )

    $normalizedRepoRoot = Get-NormalizedRepoRoot -RepoRoot $RepoRoot
    $manifestPath = Get-ProjectManifestPath -RepoRoot $normalizedRepoRoot
    if (-not (Test-Path -LiteralPath $manifestPath -PathType Leaf)) {
        throw "Manifest file was not found at '$manifestPath'."
    }

    $manifest = Read-JsonFile -Path $manifestPath
    $project = [AddonProject]::new($normalizedRepoRoot, $manifest)
    Assert-AddonManifest -Project $project
    return $project
}

function Assert-AddonManifest {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    $schemaVersion = [int]$Project.Manifest.schemaVersion
    if ($schemaVersion -ne 2) {
        throw "Manifest schemaVersion must be 2."
    }

    $toolchainVersion = [string]$Project.Manifest.toolchainVersion
    if ([string]::IsNullOrWhiteSpace($toolchainVersion)) {
        throw "Manifest toolchainVersion is required."
    }

    if ($toolchainVersion -ne $script:AddonToolchainVersion) {
        throw "Manifest toolchainVersion '$toolchainVersion' does not match toolchain version '$($script:AddonToolchainVersion)'. Run Sync-AddonToolchain."
    }

    $addonId = Get-ProjectAddonId -Project $Project
    $displayName = Get-ProjectDisplayName -Project $Project
    $version = Get-ProjectVersion -Project $Project
    $folders = Get-ProjectAddonFolders -Project $Project
    $targetSupport = Get-ProjectTargetSupport -Project $Project
    $minInstallerVersion = Get-ProjectMinInstallerVersion -Project $Project
    $tocRelativePath = Get-ProjectTocRelativePath -Project $Project

    if ([string]::IsNullOrWhiteSpace($addonId) -or
        [string]::IsNullOrWhiteSpace($displayName) -or
        [string]::IsNullOrWhiteSpace($version) -or
        [string]::IsNullOrWhiteSpace($minInstallerVersion) -or
        [string]::IsNullOrWhiteSpace($tocRelativePath)) {
        throw "Manifest is missing one of: addonId, displayName, version, minInstallerVersion, tocPath."
    }

    if ($folders.Count -ne 1) {
        throw "Manifest must define exactly one managed folder."
    }

    if ($targetSupport.Count -eq 0) {
        throw "Manifest must define at least one supported target."
    }

    if (-not (Test-AddonSemVer -Value $version)) {
        throw "Version '$version' is not valid semver."
    }

    if (-not (Test-AddonSemVer -Value $minInstallerVersion)) {
        throw "minInstallerVersion '$minInstallerVersion' is not valid semver."
    }

    $publishTimeoutSeconds = Get-ProjectPublishTimeoutSeconds -Project $Project
    if ($publishTimeoutSeconds -lt 0) {
        throw "publishTimeoutSeconds must be zero or greater."
    }
}

function Assert-GeneratedFileMarker {
    param(
        [Parameter(Mandatory)]
        [string]$Path
    )

    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        throw "Generated file was not found at '$Path'."
    }

    $firstLine = Get-Content -LiteralPath $Path -TotalCount 1
    if ($firstLine -ne $script:GeneratedMarker -and $firstLine -ne $script:GeneratedCmdMarker) {
        throw "Generated file '$Path' is missing the expected marker. Run Sync-AddonToolchain."
    }
}

function Get-TocEntries {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    $tocPath = Get-ProjectTocPath -Project $Project
    if (-not (Test-Path -LiteralPath $tocPath -PathType Leaf)) {
        throw "Expected TOC file was not found at '$tocPath'."
    }

    $tocEntries = Get-Content -LiteralPath $tocPath |
        ForEach-Object { $_.Trim() } |
        Where-Object { $_ -and -not $_.StartsWith("##") -and -not $_.StartsWith("#") }

    if (-not $tocEntries) {
        throw "No runtime files were declared in '$tocPath'."
    }

    $result = @($tocEntries)
    return ,$result
}

function Get-TocVersion {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    $tocPath = Get-ProjectTocPath -Project $Project
    $tocVersionMatch = Select-String -Path $tocPath -Pattern '^## Version:\s*(.+)$'
    if (-not $tocVersionMatch) {
        throw "Unable to read addon version from '$tocPath'."
    }

    return $tocVersionMatch.Matches[0].Groups[1].Value.Trim()
}

function Set-TocVersion {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project,

        [Parameter(Mandatory)]
        [string]$Version
    )

    $tocPath = Get-ProjectTocPath -Project $Project
    $tocContent = Get-Content -LiteralPath $tocPath -Raw
    if ($tocContent -notmatch '(?m)^## Version:\s*(.+)$') {
        throw "Unable to read addon version from '$tocPath'."
    }

    $updatedContent = [regex]::Replace($tocContent, '(?m)^## Version:\s*.+$', "## Version: $Version", 1)
    Set-Content -LiteralPath $tocPath -Value $updatedContent -Encoding utf8
}

function Read-VersionFileValue {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    $versionFilePath = Get-ProjectVersionFilePath -Project $Project
    if ($null -eq $versionFilePath) {
        return $null
    }

    if (-not (Test-Path -LiteralPath $versionFilePath -PathType Leaf)) {
        throw "Expected version file was not found at '$versionFilePath'."
    }

    $value = [string](Get-Content -LiteralPath $versionFilePath -Raw).Trim()
    if ([string]::IsNullOrWhiteSpace($value)) {
        throw "Version file '$versionFilePath' is empty."
    }

    return $value
}

function Set-VersionFileValue {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project,

        [Parameter(Mandatory)]
        [string]$Version
    )

    $versionFilePath = Get-ProjectVersionFilePath -Project $Project
    if ($null -eq $versionFilePath) {
        return
    }

    Set-Content -LiteralPath $versionFilePath -Value ("{0}`n" -f $Version) -Encoding ascii
}

function Assert-AddonProjectStructure {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project,

        [string]$Action = "validate",

        [switch]$SkipVersionChecks
    )

    $tocPath = Get-ProjectTocPath -Project $Project
    $tocContentRoot = Get-ProjectTocContentRoot -Project $Project
    $linkSourcePath = Get-ProjectLinkSourcePath -Project $Project
    $addonFolder = Get-ProjectAddonFolder -Project $Project
    $manifestVersion = Get-ProjectVersion -Project $Project
    $versionFileValue = Read-VersionFileValue -Project $Project

    if (-not (Test-Path -LiteralPath $tocPath -PathType Leaf)) {
        throw "Expected TOC file was not found at '$tocPath'."
    }

    if (-not (Test-Path -LiteralPath $tocContentRoot -PathType Container)) {
        throw "TOC content root was not found at '$tocContentRoot'."
    }

    if (-not (Test-Path -LiteralPath $linkSourcePath -PathType Container)) {
        throw "Link source path was not found at '$linkSourcePath'."
    }

    if (-not $SkipVersionChecks) {
        $tocVersion = Get-TocVersion -Project $Project
        if ($tocVersion -ne $manifestVersion) {
            throw "TOC version '$tocVersion' does not match manifest version '$manifestVersion'."
        }

        if ($null -ne $versionFileValue -and $versionFileValue -ne $manifestVersion) {
            throw "Version file version '$versionFileValue' does not match manifest version '$manifestVersion'."
        }
    }

    foreach ($entry in (Get-TocEntries -Project $Project)) {
        if ([System.IO.Path]::IsPathRooted($entry) -or $entry.Contains("..")) {
            throw "TOC entry '$entry' is not valid."
        }

        $sourcePath = [System.IO.Path]::GetFullPath((Join-Path $tocContentRoot $entry))
        if (-not (Test-Path -LiteralPath $sourcePath -PathType Leaf)) {
            throw "TOC entry '$entry' was not found at '$sourcePath'."
        }
    }

    if ($Action -eq "coverage") {
        $coverageScriptPath = Get-ProjectCoverageScriptPath -Project $Project
        if ($null -eq $coverageScriptPath) {
            throw "Coverage is not configured for $(Get-ProjectDisplayName -Project $Project)."
        }

        if (-not (Test-Path -LiteralPath $coverageScriptPath -PathType Leaf)) {
            throw "Coverage script was not found at '$coverageScriptPath'."
        }
    }

    if ([string]::IsNullOrWhiteSpace($addonFolder)) {
        throw "Addon folder is required."
    }
}

function New-StageRoot {
    param(
        [Parameter(Mandatory)]
        [string]$AddonFolder,

        [Parameter(Mandatory)]
        [string]$Purpose
    )

    $stageBase = Join-Path ([System.IO.Path]::GetTempPath()) "addon-dev-stage"
    New-Item -ItemType Directory -Path $stageBase -Force | Out-Null

    $stageRoot = Join-Path $stageBase ("{0}-{1}-{2}" -f $AddonFolder, $Purpose, [guid]::NewGuid().ToString("N"))
    New-Item -ItemType Directory -Path $stageRoot -Force | Out-Null
    return $stageRoot
}

function Remove-PathIfPresent {
    param(
        [Parameter(Mandatory)]
        [string]$Path
    )

    if (Test-Path -LiteralPath $Path) {
        Remove-Item -LiteralPath $Path -Recurse -Force -ErrorAction Stop
    }
}

function Stage-RuntimeFromToc {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project,

        [Parameter(Mandatory)]
        [string]$StageRoot
    )

    $addonFolder = Get-ProjectAddonFolder -Project $Project
    $tocPath = Get-ProjectTocPath -Project $Project
    $contentRoot = Get-ProjectTocContentRoot -Project $Project
    $stagedAddonPath = Join-Path $StageRoot $addonFolder

    New-Item -ItemType Directory -Path $stagedAddonPath -Force | Out-Null
    Copy-Item -LiteralPath $tocPath -Destination (Join-Path $stagedAddonPath ("{0}.toc" -f $addonFolder)) -Force

    foreach ($entry in (Get-TocEntries -Project $Project)) {
        $sourcePath = Join-Path $contentRoot $entry
        $destinationPath = Join-Path $stagedAddonPath $entry
        $destinationDir = Split-Path -Parent $destinationPath
        if ($destinationDir) {
            New-Item -ItemType Directory -Path $destinationDir -Force | Out-Null
        }

        Copy-Item -LiteralPath $sourcePath -Destination $destinationPath -Force
    }

    return $stagedAddonPath
}

function Get-TargetAddonDir {
    param(
        [Parameter(Mandatory)]
        [string]$WowPath,

        [Parameter(Mandatory)]
        [string]$Flavor
    )

    $directAddonDir = Join-Path $WowPath "Interface\AddOns"
    if (Test-Path -LiteralPath $directAddonDir -PathType Container) {
        return $directAddonDir
    }

    return Join-Path $WowPath ("_{0}_\Interface\AddOns" -f $Flavor)
}

function Test-IsAdministrator {
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = [Security.Principal.WindowsPrincipal]::new($identity)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Format-Argument {
    param(
        [AllowNull()]
        [string]$Value
    )

    if ($null -eq $Value) {
        return '""'
    }

    return '"' + ($Value -replace '"', '\"') + '"'
}

function Build-RelaunchArgumentList {
    param(
        [Parameter(Mandatory)]
        [string]$EntryScriptPath,

        [Parameter(Mandatory)]
        [string]$Action,

        [Parameter(Mandatory)]
        [string]$WowPath,

        [Parameter(Mandatory)]
        [string]$Flavor,

        [Parameter(Mandatory)]
        [bool]$PauseOnExit
    )

    $arguments = @(
        "-NoProfile"
        "-ExecutionPolicy"
        "Bypass"
        "-File"
        (Format-Argument -Value $EntryScriptPath)
        "-Action"
        (Format-Argument -Value $Action)
        "-WowPath"
        (Format-Argument -Value $WowPath)
        "-Flavor"
        (Format-Argument -Value $Flavor)
    )

    if ($PauseOnExit) {
        $arguments += "-PauseOnExit"
    }

    return $arguments -join " "
}

function Request-Elevation {
    param(
        [Parameter(Mandatory)]
        [string]$ActionDescription,

        [Parameter(Mandatory)]
        [string]$EntryScriptPath,

        [Parameter(Mandatory)]
        [string]$Action,

        [Parameter(Mandatory)]
        [string]$WowPath,

        [Parameter(Mandatory)]
        [string]$Flavor,

        [Parameter(Mandatory)]
        [bool]$PauseOnExit
    )

    if ([string]::IsNullOrWhiteSpace($EntryScriptPath)) {
        throw "$ActionDescription requires administrator privileges. Re-run PowerShell as Administrator."
    }

    Start-Process PowerShell -Verb RunAs -ArgumentList (Build-RelaunchArgumentList -EntryScriptPath $EntryScriptPath -Action $Action -WowPath $WowPath -Flavor $Flavor -PauseOnExit $PauseOnExit) | Out-Null
    Write-Host "$ActionDescription requires elevation. Opened an administrator PowerShell to continue." -ForegroundColor Yellow
    throw [System.OperationCanceledException]::new("ElevationRelaunched")
}

function Ensure-WriteAccess {
    param(
        [Parameter(Mandatory)]
        [string]$DirectoryPath,

        [Parameter(Mandatory)]
        [string]$ActionDescription,

        [Parameter(Mandatory)]
        [bool]$RequireAdministrator,

        [Parameter(Mandatory)]
        [string]$ProbeName,

        [Parameter(Mandatory)]
        [string]$EntryScriptPath,

        [Parameter(Mandatory)]
        [string]$Action,

        [Parameter(Mandatory)]
        [string]$WowPath,

        [Parameter(Mandatory)]
        [string]$Flavor,

        [Parameter(Mandatory)]
        [bool]$PauseOnExit
    )

    if ($RequireAdministrator -and -not (Test-IsAdministrator)) {
        Request-Elevation -ActionDescription $ActionDescription -EntryScriptPath $EntryScriptPath -Action $Action -WowPath $WowPath -Flavor $Flavor -PauseOnExit $PauseOnExit
    }

    $probePath = Join-Path $DirectoryPath (".{0}-write-test" -f $ProbeName.ToLowerInvariant())
    try {
        New-Item -ItemType File -Path $probePath -Force -ErrorAction Stop | Out-Null
        Remove-Item -Path $probePath -Force -ErrorAction Stop
    }
    catch {
        if (-not (Test-IsAdministrator)) {
            Request-Elevation -ActionDescription $ActionDescription -EntryScriptPath $EntryScriptPath -Action $Action -WowPath $WowPath -Flavor $Flavor -PauseOnExit $PauseOnExit
        }

        throw "$ActionDescription requires write access to '$DirectoryPath'. $($_.Exception.Message)"
    }
}

function Test-AddonDevAutoPauseOnExit {
    try {
        $currentProcess = Get-CimInstance -ClassName Win32_Process -Filter ("ProcessId = {0}" -f $PID) -ErrorAction Stop
        if ($null -eq $currentProcess -or $currentProcess.ParentProcessId -le 0) {
            return $false
        }

        $parentProcess = Get-Process -Id $currentProcess.ParentProcessId -ErrorAction Stop
        return $parentProcess.ProcessName -ieq "explorer"
    }
    catch {
        return $false
    }
}

function Wait-ForAddonDevExitAcknowledgement {
    param(
        [Parameter(Mandatory)]
        [bool]$PauseOnExit
    )

    $shouldPause = $PauseOnExit -or (Test-AddonDevAutoPauseOnExit)
    if (-not $shouldPause) {
        return
    }

    Write-Host ""
    Write-Host "Press any key to close this window..." -ForegroundColor DarkGray
    [void][System.Console]::ReadKey($true)
}

function Invoke-Tool {
    param(
        [Parameter(Mandatory)]
        [string]$FilePath,

        [string[]]$Arguments = @(),

        [switch]$IgnoreExitCode
    )

    $result = & $FilePath @Arguments 2>&1
    if (-not $IgnoreExitCode -and $LASTEXITCODE -ne 0) {
        $rendered = if ($result) { ($result | Out-String).Trim() } else { "" }
        if ($rendered) {
            throw "$FilePath $($Arguments -join ' ') failed: $rendered"
        }

        throw "$FilePath $($Arguments -join ' ') failed with exit code $LASTEXITCODE."
    }

    return $result
}

function Get-OriginRepository {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    $remoteUrl = (Invoke-Tool -FilePath "git" -Arguments @("-C", $Project.RepoRoot, "remote", "get-url", "origin")) | Select-Object -First 1
    $remoteUrl = [string]$remoteUrl

    if ($remoteUrl -match 'github\.com[:/](?<owner>[^/]+)/(?<repo>[^/.]+?)(?:\.git)?$') {
        return @{
            Owner = $Matches.owner
            Repo  = $Matches.repo
            Url   = $remoteUrl
        }
    }

    throw "Origin remote '$remoteUrl' is not a supported GitHub repository URL."
}

function Get-GitStatusText {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    return ((Invoke-Tool -FilePath "git" -Arguments @("-C", $Project.RepoRoot, "status", "--porcelain")) | Out-String)
}

function Get-LatestRelease {
    param(
        [Parameter(Mandatory)]
        [string]$Owner,

        [Parameter(Mandatory)]
        [string]$Repo
    )

    $headers = @{ "User-Agent" = "AddonDevTooling-Release" }
    try {
        return Invoke-RestMethod -Headers $headers -Uri "https://api.github.com/repos/$Owner/$Repo/releases/latest"
    }
    catch {
        $response = $_.Exception.Response
        if ($response -and [int]$response.StatusCode -eq 404) {
            return $null
        }

        throw
    }
}

function Test-RemoteTagExists {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project,

        [Parameter(Mandatory)]
        [string]$TagName
    )

    $refs = Invoke-Tool -FilePath "git" -Arguments @("-C", $Project.RepoRoot, "ls-remote", "--tags", "origin", "refs/tags/$TagName")
    return -not [string]::IsNullOrWhiteSpace((($refs | Out-String).Trim()))
}

function Wait-ForPublishedRelease {
    param(
        [Parameter(Mandatory)]
        [string]$Owner,

        [Parameter(Mandatory)]
        [string]$Repo,

        [Parameter(Mandatory)]
        [string]$TagName,

        [Parameter(Mandatory)]
        [string]$ExpectedZipName,

        [Parameter(Mandatory)]
        [int]$TimeoutSeconds
    )

    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    do {
        $release = Get-LatestRelease -Owner $Owner -Repo $Repo
        if ($release -and $release.tag_name -eq $TagName) {
            $assetNames = @($release.assets | ForEach-Object { $_.name })
            if ($assetNames -contains "addon-manifest.json" -and $assetNames -contains $ExpectedZipName) {
                return $release
            }
        }

        Start-Sleep -Seconds 5
    } while ((Get-Date) -lt $deadline)

    return $null
}

function Update-ProjectVersion {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project,

        [Parameter(Mandatory)]
        [string]$Version
    )

    if (-not (Test-AddonSemVer -Value $Version)) {
        throw "Version '$Version' is not valid semver."
    }

    if ([string]$Project.Manifest.version -ne $Version) {
        $Project.Manifest.version = $Version
        Write-JsonFile -Path (Get-ProjectManifestPath -RepoRoot $Project.RepoRoot) -Value $Project.Manifest
    }

    Set-VersionFileValue -Project $Project -Version $Version

    if ((Get-TocVersion -Project $Project) -ne $Version) {
        Set-TocVersion -Project $Project -Version $Version
    }
}

function Get-ResolvedReleaseVersion {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project,

        [string]$Version
    )

    if (-not [string]::IsNullOrWhiteSpace($Version)) {
        return $Version.Trim()
    }

    $versionFileValue = Read-VersionFileValue -Project $Project
    if ($null -ne $versionFileValue) {
        return $versionFileValue
    }

    return Get-ProjectVersion -Project $Project
}

function Get-ManagedVersionRelativePaths {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project
    )

    $paths = [System.Collections.Generic.List[string]]::new()
    $paths.Add($script:ManifestFileName)
    $paths.Add((Get-ProjectTocRelativePath -Project $Project))

    $versionFileRelativePath = Get-ProjectVersionFileRelativePath -Project $Project
    if (-not [string]::IsNullOrWhiteSpace($versionFileRelativePath)) {
        $paths.Add($versionFileRelativePath)
    }

    $result = @($paths | Select-Object -Unique)
    return ,$result
}

function Commit-ManagedVersionFiles {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project,

        [Parameter(Mandatory)]
        [string]$Version
    )

    $paths = Get-ManagedVersionRelativePaths -Project $Project
    $gitAddArguments = @("-C", $Project.RepoRoot, "add", "--") + $paths
    Invoke-Tool -FilePath "git" -Arguments $gitAddArguments
    Invoke-Tool -FilePath "git" -Arguments @("-C", $Project.RepoRoot, "commit", "-m", "chore: release v$Version")
}

function Build-InstallerReadyReleaseAsset {
    param(
        [Parameter(Mandatory)]
        [AddonProject]$Project,

        [Parameter(Mandatory)]
        [string]$OutputDir,

        [Parameter(Mandatory)]
        [AllowEmptyString()]
        [string]$ReleaseNotes
    )

    $addonId = Get-ProjectAddonId -Project $Project
    $displayName = Get-ProjectDisplayName -Project $Project
    $version = Get-ProjectVersion -Project $Project
    $targetSupport = Get-ProjectTargetSupport -Project $Project
    $addonFolder = Get-ProjectAddonFolder -Project $Project
    $minInstallerVersion = Get-ProjectMinInstallerVersion -Project $Project
    $stageRoot = Join-Path $OutputDir (".stage-{0}-{1}" -f $addonFolder, $version)
    $stagedAddonPath = Stage-RuntimeFromToc -Project $Project -StageRoot $stageRoot
    $zipName = "{0}-v{1}.zip" -f $addonFolder, $version
    $zipPath = Join-Path $OutputDir $zipName
    $manifestPath = Join-Path $OutputDir "addon-manifest.json"

    try {
        if (Test-Path -LiteralPath $zipPath) {
            Remove-Item -LiteralPath $zipPath -Force
        }

        if (Test-Path -LiteralPath $manifestPath) {
            Remove-Item -LiteralPath $manifestPath -Force
        }

        Compress-Archive -Path $stagedAddonPath -DestinationPath $zipPath -Force

        $hash = (Get-FileHash -LiteralPath $zipPath -Algorithm SHA256).Hash.ToLowerInvariant()

        Add-Type -AssemblyName System.IO.Compression.FileSystem
        $archive = [System.IO.Compression.ZipFile]::OpenRead($zipPath)
        try {
            $rootNames = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
            foreach ($entry in $archive.Entries) {
                if ([string]::IsNullOrEmpty($entry.FullName)) {
                    continue
                }

                $normalizedEntry = $entry.FullName.Replace([char]92, '/')
                $trimmed = $normalizedEntry.TrimStart('./').TrimEnd('/')
                if ([string]::IsNullOrEmpty($trimmed)) {
                    continue
                }

                $rootSegment = $trimmed.Split('/')[0]
                if (-not [string]::IsNullOrEmpty($rootSegment)) {
                    [void]$rootNames.Add($rootSegment)
                }
            }

            if ($rootNames.Count -ne 1 -or -not $rootNames.Contains($addonFolder)) {
                $foundRoots = ($rootNames | Sort-Object) -join ', '
                throw "Zip root validation failed. Expected only '$addonFolder' at the archive root, found: $foundRoots"
            }
        }
        finally {
            $archive.Dispose()
        }

        $manifest = [ordered]@{
            schemaVersion       = 1
            addonId             = $addonId
            displayName         = $displayName
            version             = $version
            targetSupport       = $targetSupport
            folders             = @($addonFolder)
            assetName           = $zipName
            sha256              = $hash
            minInstallerVersion = $minInstallerVersion
            releaseNotes        = $ReleaseNotes
        }

        $manifest | ConvertTo-Json -Depth 4 | Set-Content -LiteralPath $manifestPath -Encoding utf8
        $writtenManifest = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json

        if ($writtenManifest.addonId -ne $addonId) {
            throw "Manifest validation failed: addonId must be '$addonId'."
        }

        if (@($writtenManifest.folders).Count -ne 1 -or @($writtenManifest.folders)[0] -ne $addonFolder) {
            throw "Manifest validation failed: folders do not match the addon folder."
        }

        if ($writtenManifest.assetName -ne $zipName) {
            throw "Manifest validation failed: assetName does not match the zip asset name."
        }

        if ($writtenManifest.minInstallerVersion -ne $minInstallerVersion) {
            throw "Manifest validation failed: minInstallerVersion does not match the manifest."
        }

        if ($writtenManifest.version -ne $version) {
            throw "Manifest validation failed: version must match the release version."
        }

        return [pscustomobject]@{
            ZipName      = $zipName
            ZipPath      = $zipPath
            ManifestPath = $manifestPath
        }
    }
    finally {
        Remove-PathIfPresent -Path $stageRoot
    }
}

function Invoke-AddonAction {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$RepoRoot,

        [string]$Action = "install",

        [string]$WowPath,

        [string]$Flavor = "retail",

        [switch]$PauseOnExit,

        [string]$EntryScriptPath
    )

    $exitCode = 0
    $project = Resolve-AddonProject -RepoRoot $RepoRoot

    try {
        $normalizedAction = if ([string]::IsNullOrWhiteSpace($Action)) { "install" } else { $Action.ToLowerInvariant() }
        if (-not ($script:SupportedActions -contains $normalizedAction)) {
            $usage = ".\" + [System.IO.Path]::GetFileName($EntryScriptPath) + " -Action [" + ($script:SupportedActions -join "|") + "] -Flavor [retail|classic|classic_era|ptr]"
            throw "Unknown action: $Action`nUse: $usage"
        }

        Assert-AddonProjectStructure -Project $project -Action $normalizedAction

        if (-not $PSBoundParameters.ContainsKey("WowPath")) {
            if ($Flavor -eq "ptr") {
                $WowPath = Get-ProjectPtrWowPath -Project $project
            }
            else {
                $WowPath = Get-ProjectDefaultWowPath -Project $project
            }
        }

        $addonName = Get-ProjectDisplayName -Project $project
        $addonFolder = Get-ProjectAddonFolder -Project $project
        $targetAddonDir = Get-TargetAddonDir -WowPath $WowPath -Flavor $Flavor
        $targetPath = Join-Path $targetAddonDir $addonFolder

        switch ($normalizedAction) {
            "install" {
                $stageRoot = New-StageRoot -AddonFolder $addonFolder -Purpose "install"
                try {
                    $stagedAddonPath = Stage-RuntimeFromToc -Project $project -StageRoot $stageRoot
                    if (-not (Test-Path -LiteralPath $targetAddonDir -PathType Container)) {
                        throw "Target addon directory was not found at '$targetAddonDir'."
                    }

                    Ensure-WriteAccess -DirectoryPath $targetAddonDir -ActionDescription ("Installing {0}" -f $addonName) -RequireAdministrator:$false -ProbeName $addonFolder -EntryScriptPath $EntryScriptPath -Action $normalizedAction -WowPath $WowPath -Flavor $Flavor -PauseOnExit:$PauseOnExit
                    Write-Host ("Installing {0} to {1}..." -f $addonName, $targetPath) -ForegroundColor Cyan
                    Remove-PathIfPresent -Path $targetPath
                    Copy-Item -Recurse -Path $stagedAddonPath -Destination $targetPath -ErrorAction Stop
                    Write-Host ("Installed {0} to {1}" -f $addonName, $targetPath) -ForegroundColor Green
                }
                finally {
                    Remove-PathIfPresent -Path $stageRoot
                }
                return
            }
            "link" {
                $linkSourcePath = Get-ProjectLinkSourcePath -Project $project
                if (-not (Test-Path -LiteralPath $targetAddonDir -PathType Container)) {
                    throw "Target addon directory was not found at '$targetAddonDir'."
                }

                Ensure-WriteAccess -DirectoryPath $targetAddonDir -ActionDescription ("Linking {0}" -f $addonName) -RequireAdministrator:$true -ProbeName $addonFolder -EntryScriptPath $EntryScriptPath -Action $normalizedAction -WowPath $WowPath -Flavor $Flavor -PauseOnExit:$PauseOnExit
                Write-Host ("Creating Symbolic Link for {0}..." -f $addonName) -ForegroundColor Cyan
                Remove-PathIfPresent -Path $targetPath
                New-Item -ItemType SymbolicLink -Path $targetPath -Target $linkSourcePath -ErrorAction Stop | Out-Null
                Write-Host "Link created! Changes in this folder will reflect instantly in-game (after /reload)." -ForegroundColor Green
                return
            }
            "clean" {
                if (Test-Path -LiteralPath $targetPath) {
                    if (-not (Test-Path -LiteralPath $targetAddonDir -PathType Container)) {
                        throw "Target addon directory was not found at '$targetAddonDir'."
                    }

                    Ensure-WriteAccess -DirectoryPath $targetAddonDir -ActionDescription ("Cleaning {0}" -f $addonName) -RequireAdministrator:$false -ProbeName $addonFolder -EntryScriptPath $EntryScriptPath -Action $normalizedAction -WowPath $WowPath -Flavor $Flavor -PauseOnExit:$PauseOnExit
                    Write-Host ("Cleaning {0} from {1}..." -f $addonName, $targetPath) -ForegroundColor Yellow
                    Remove-PathIfPresent -Path $targetPath
                    Write-Host "Cleaned." -ForegroundColor Green
                    return
                }

                Write-Host "Addon not found in target path. Nothing to clean."
                return
            }
            "dist" {
                $version = Get-ProjectVersion -Project $project
                $zipPath = Join-Path $project.RepoRoot ("{0}-v{1}.zip" -f $addonFolder, $version)
                $stageRoot = New-StageRoot -AddonFolder $addonFolder -Purpose "dist"
                try {
                    $stagedAddonPath = Stage-RuntimeFromToc -Project $project -StageRoot $stageRoot
                    Write-Host ("Creating distribution zip: {0}" -f $zipPath) -ForegroundColor Cyan
                    if (Test-Path -LiteralPath $zipPath) {
                        Remove-Item -LiteralPath $zipPath -Force
                    }

                    Compress-Archive -Path $stagedAddonPath -DestinationPath $zipPath -Force
                    Write-Host ("Created {0}" -f $zipPath) -ForegroundColor Green
                }
                finally {
                    Remove-PathIfPresent -Path $stageRoot
                }
                return
            }
            "coverage" {
                $coverageScriptPath = Get-ProjectCoverageScriptPath -Project $project
                $coverageArguments = Get-ProjectCoverageArguments -Project $project
                Write-Host "Running Lua coverage..." -ForegroundColor Cyan
                & $coverageScriptPath @coverageArguments
                if ($LASTEXITCODE -ne 0) {
                    throw "Coverage script exited with code $LASTEXITCODE."
                }

                Write-Host "Coverage complete." -ForegroundColor Green
                return
            }
        }
    }
    catch [System.OperationCanceledException] {
        if ($_.Exception.Message -ne "ElevationRelaunched") {
            Write-Error $_.Exception.Message
            $exitCode = 1
        }
    }
    catch {
        Write-Error $_.Exception.Message
        $exitCode = 1
    }
    finally {
        Wait-ForAddonDevExitAcknowledgement -PauseOnExit:$PauseOnExit
    }

    if ($exitCode -ne 0) {
        exit $exitCode
    }
}

function Invoke-AddonRelease {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$RepoRoot,

        [string]$OutputDir,

        [string]$ReleaseNotes = "",

        [string]$Version,

        [string]$ExpectedVersion,

        [switch]$PublishRelease,

        [int]$PublishTimeoutSeconds
    )

    $project = Resolve-AddonProject -RepoRoot $RepoRoot
    Assert-AddonProjectStructure -Project $project -Action "dist" -SkipVersionChecks

    if (-not $PSBoundParameters.ContainsKey("OutputDir")) {
        $OutputDir = Get-ProjectReleaseOutputDir -Project $project
    }

    if (-not $PSBoundParameters.ContainsKey("PublishTimeoutSeconds")) {
        $PublishTimeoutSeconds = Get-ProjectPublishTimeoutSeconds -Project $project
    }

    if ($PublishTimeoutSeconds -lt 0) {
        throw "PublishTimeoutSeconds must be zero or greater."
    }

    if ($PublishRelease) {
        $prePublishStatus = Get-GitStatusText -Project $project
        if (-not [string]::IsNullOrWhiteSpace($prePublishStatus)) {
            throw "Refusing to publish with uncommitted changes in '$($project.RepoRoot)'. Commit or stash changes first."
        }
    }

    $resolvedVersion = Get-ResolvedReleaseVersion -Project $project -Version $Version
    if (-not (Test-AddonSemVer -Value $resolvedVersion)) {
        throw "Version '$resolvedVersion' is not valid semver."
    }

    if ($ExpectedVersion -and $ExpectedVersion -ne $resolvedVersion) {
        throw "Resolved release version '$resolvedVersion' does not match expected version '$ExpectedVersion'."
    }

    Update-ProjectVersion -Project $project -Version $resolvedVersion
    Assert-AddonProjectStructure -Project $project -Action "dist"

    $resolvedOutputDir = if ([System.IO.Path]::IsPathRooted($OutputDir)) {
        [System.IO.Path]::GetFullPath($OutputDir)
    }
    else {
        [System.IO.Path]::GetFullPath((Join-Path $project.RepoRoot $OutputDir))
    }

    New-Item -ItemType Directory -Path $resolvedOutputDir -Force | Out-Null
    $bundle = Build-InstallerReadyReleaseAsset -Project $project -OutputDir $resolvedOutputDir -ReleaseNotes $ReleaseNotes

    Write-Host "Built release assets:" -ForegroundColor Green
    Write-Host "- $($bundle.ZipPath)"
    Write-Host "- $($bundle.ManifestPath)"

    if (-not $PublishRelease) {
        return
    }

    $statusOutput = Get-GitStatusText -Project $project
    if (-not [string]::IsNullOrWhiteSpace($statusOutput)) {
        Commit-ManagedVersionFiles -Project $project -Version $resolvedVersion
    }

    $tagName = "v$resolvedVersion"
    $repoInfo = Get-OriginRepository -Project $project
    $currentHead = [string](Invoke-Tool -FilePath "git" -Arguments @("-C", $project.RepoRoot, "rev-parse", "HEAD") | Select-Object -First 1)
    $localTagCommit = [string](Invoke-Tool -FilePath "git" -Arguments @("-C", $project.RepoRoot, "rev-parse", "-q", "--verify", "refs/tags/$tagName^{}") -IgnoreExitCode | Select-Object -First 1)
    if ([string]::IsNullOrWhiteSpace($localTagCommit)) {
        Write-Host ""
        Write-Host "Creating local tag $tagName at $currentHead" -ForegroundColor Cyan
        Invoke-Tool -FilePath "git" -Arguments @("-C", $project.RepoRoot, "tag", "-a", $tagName, "-m", "$(Get-ProjectDisplayName -Project $project) $tagName")
    }
    elseif ($localTagCommit -ne $currentHead) {
        throw "Local tag '$tagName' points to $localTagCommit, but HEAD is $currentHead. Move or delete the tag before publishing."
    }
    else {
        Write-Host ""
        Write-Host "Local tag $tagName already exists at HEAD." -ForegroundColor Cyan
    }

    if (-not (Test-RemoteTagExists -Project $project -TagName $tagName)) {
        Write-Host "Pushing tag $tagName to origin..." -ForegroundColor Cyan
        Invoke-Tool -FilePath "git" -Arguments @("-C", $project.RepoRoot, "push", "origin", $tagName)
    }
    else {
        Write-Host "Remote tag $tagName already exists." -ForegroundColor Cyan
    }

    $latestRelease = Get-LatestRelease -Owner $repoInfo.Owner -Repo $repoInfo.Repo
    if ($latestRelease -and $latestRelease.tag_name -eq $tagName) {
        $assetNames = @($latestRelease.assets | ForEach-Object { $_.name })
        if ($assetNames -contains "addon-manifest.json" -and $assetNames -contains $bundle.ZipName) {
            Write-Host "Release $tagName is already published with installer assets." -ForegroundColor Green
            return
        }
    }

    Write-Host "Waiting for GitHub Actions to publish release $tagName..." -ForegroundColor Cyan
    $publishedRelease = Wait-ForPublishedRelease -Owner $repoInfo.Owner -Repo $repoInfo.Repo -TagName $tagName -ExpectedZipName $bundle.ZipName -TimeoutSeconds $PublishTimeoutSeconds
    if ($publishedRelease) {
        Write-Host "Published release is now visible to the installer:" -ForegroundColor Green
        Write-Host "- $($publishedRelease.html_url)"
        return
    }

    throw "Tag $tagName was pushed, but GitHub did not publish a matching release within $PublishTimeoutSeconds seconds."
}

function Test-AddonProject {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$RepoRoot,

        [switch]$IncludePackaging = $true
    )

    $project = Resolve-AddonProject -RepoRoot $RepoRoot
    Assert-AddonProjectStructure -Project $project

    $generatedFiles = Get-ProjectGeneratedFileMap -Project $project
    foreach ($path in @($generatedFiles.ModulePath, $generatedFiles.BuildScriptPath, $generatedFiles.ValidationScriptPath, $generatedFiles.InstallScriptPath, $generatedFiles.InstallCmdPath)) {
        Assert-GeneratedFileMarker -Path $path
    }

    if ($IncludePackaging) {
        $tempOutputDir = Join-Path ([System.IO.Path]::GetTempPath()) ("addon-dev-validation-{0}" -f [guid]::NewGuid().ToString("N"))
        try {
            New-Item -ItemType Directory -Path $tempOutputDir -Force | Out-Null
            [void](Build-InstallerReadyReleaseAsset -Project $project -OutputDir $tempOutputDir -ReleaseNotes "")
        }
        finally {
            Remove-PathIfPresent -Path $tempOutputDir
        }
    }

    Write-Host "Addon project validation passed." -ForegroundColor Green
}

function New-GeneratedInstallScriptContent {
    return @'
# Generated by AddonDevTooling. Do not edit manually.
param(
    [Parameter(Mandatory = $false)]
    [string]$Action = "install",

    [Parameter(Mandatory = $false)]
    [string]$WowPath,

    [Parameter(Mandatory = $false)]
    [string]$Flavor = "retail",

    [Parameter(Mandatory = $false)]
    [switch]$PauseOnExit
)

$modulePath = Join-Path $PSScriptRoot "scripts\AddonDevTools.psm1"
if (-not (Test-Path -LiteralPath $modulePath -PathType Leaf)) {
    throw "AddonDevTools module was not found at '$modulePath'."
}

Import-Module $modulePath -Force

$invokeParams = @{
    RepoRoot        = $PSScriptRoot
    Action          = $Action
    Flavor          = $Flavor
    PauseOnExit     = [bool]$PauseOnExit
    EntryScriptPath = $PSCommandPath
}

if ($PSBoundParameters.ContainsKey("WowPath")) {
    $invokeParams.WowPath = $WowPath
}

Invoke-AddonAction @invokeParams
'@
}

function New-GeneratedInstallCmdContent {
    param(
        [Parameter(Mandatory)]
        [string]$InstallScriptName
    )

    return @"
:: Generated by AddonDevTooling. Do not edit manually.
@echo off
setlocal
powershell.exe -NoProfile -ExecutionPolicy Bypass -File "%~dp0$InstallScriptName" -PauseOnExit %*
set "exitCode=%ERRORLEVEL%"
exit /b %exitCode%
"@
}

function New-GeneratedBuildScriptContent {
    return @'
# Generated by AddonDevTooling. Do not edit manually.
param(
    [string]$OutputDir,

    [string]$ReleaseNotes = "",

    [string]$Version,

    [string]$ExpectedVersion,

    [switch]$PublishRelease,

    [int]$PublishTimeoutSeconds
)

$modulePath = Join-Path $PSScriptRoot "AddonDevTools.psm1"
if (-not (Test-Path -LiteralPath $modulePath -PathType Leaf)) {
    throw "AddonDevTools module was not found at '$modulePath'."
}

Import-Module $modulePath -Force

$invokeParams = @{
    RepoRoot     = (Split-Path -Parent $PSScriptRoot)
    ReleaseNotes = $ReleaseNotes
}

if ($PSBoundParameters.ContainsKey("OutputDir")) {
    $invokeParams.OutputDir = $OutputDir
}

if ($PSBoundParameters.ContainsKey("Version")) {
    $invokeParams.Version = $Version
}

if ($PSBoundParameters.ContainsKey("ExpectedVersion")) {
    $invokeParams.ExpectedVersion = $ExpectedVersion
}

if ($PublishRelease) {
    $invokeParams.PublishRelease = $true
}

if ($PSBoundParameters.ContainsKey("PublishTimeoutSeconds")) {
    $invokeParams.PublishTimeoutSeconds = $PublishTimeoutSeconds
}

Invoke-AddonRelease @invokeParams
'@
}

function New-GeneratedValidationScriptContent {
    return @'
# Generated by AddonDevTooling. Do not edit manually.
param(
    [switch]$SkipPackaging
)

$modulePath = Join-Path $PSScriptRoot "AddonDevTools.psm1"
if (-not (Test-Path -LiteralPath $modulePath -PathType Leaf)) {
    throw "AddonDevTools module was not found at '$modulePath'."
}

Import-Module $modulePath -Force
Test-AddonProject -RepoRoot (Split-Path -Parent $PSScriptRoot) -IncludePackaging:(-not $SkipPackaging)
'@
}

function Write-GeneratedFile {
    param(
        [Parameter(Mandatory)]
        [string]$Path,

        [Parameter(Mandatory)]
        [string]$Content
    )

    $parent = Split-Path -Parent $Path
    if (-not [string]::IsNullOrWhiteSpace($parent)) {
        New-Item -ItemType Directory -Path $parent -Force | Out-Null
    }

    Set-Content -LiteralPath $Path -Value $Content -Encoding utf8
}

function Get-CurrentModulePath {
    $module = $MyInvocation.MyCommand.Module
    if ($null -eq $module -or [string]::IsNullOrWhiteSpace($module.Path)) {
        return $null
    }

    return $module.Path
}

function Sync-AddonToolchain {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$RepoRoot,

        [string]$SourceModulePath
    )

    $project = Resolve-AddonProject -RepoRoot $RepoRoot
    $generatedFiles = Get-ProjectGeneratedFileMap -Project $project

    if (-not $PSBoundParameters.ContainsKey("SourceModulePath")) {
        $SourceModulePath = Get-CurrentModulePath
        if ([string]::IsNullOrWhiteSpace($SourceModulePath)) {
            throw "SourceModulePath is required when the current module path cannot be determined."
        }
    }

    if (-not (Test-Path -LiteralPath $SourceModulePath -PathType Leaf)) {
        throw "Source module was not found at '$SourceModulePath'."
    }

    $project.Manifest.toolchainVersion = $script:AddonToolchainVersion
    Write-JsonFile -Path (Get-ProjectManifestPath -RepoRoot $project.RepoRoot) -Value $project.Manifest

    Copy-Item -LiteralPath $SourceModulePath -Destination $generatedFiles.ModulePath -Force
    Write-GeneratedFile -Path $generatedFiles.BuildScriptPath -Content (New-GeneratedBuildScriptContent)
    Write-GeneratedFile -Path $generatedFiles.ValidationScriptPath -Content (New-GeneratedValidationScriptContent)

    $installScriptName = [System.IO.Path]::GetFileName($generatedFiles.InstallScriptPath)
    Write-GeneratedFile -Path $generatedFiles.InstallScriptPath -Content (New-GeneratedInstallScriptContent)
    Write-GeneratedFile -Path $generatedFiles.InstallCmdPath -Content (New-GeneratedInstallCmdContent -InstallScriptName $installScriptName)

    if (Test-Path -LiteralPath $generatedFiles.LegacyModulePath -PathType Leaf) {
        Remove-Item -LiteralPath $generatedFiles.LegacyModulePath -Force
    }
}

function New-AddonProject {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$RepoRoot,

        [Parameter(Mandatory)]
        [string]$AddonId,

        [Parameter(Mandatory)]
        [string]$DisplayName,

        [string]$AddonFolder,

        [string]$Version = "0.1.0",

        [string[]]$TargetSupport = @("Bronzebeard", "CoA"),

        [string]$TocPath,

        [string]$TocContentRoot,

        [string]$DefaultWowPath = $script:DefaultWowPath,

        [string]$PtrWowPath = $script:DefaultPtrWowPath,

        [string]$VersionFilePath,

        [string]$CoverageScriptPath,

        [string[]]$CoverageArguments = @()
    )

    $resolvedRepoRoot = [System.IO.Path]::GetFullPath($RepoRoot)
    if ([string]::IsNullOrWhiteSpace($AddonFolder)) {
        $AddonFolder = $DisplayName
    }

    if ([string]::IsNullOrWhiteSpace($TocPath)) {
        $TocPath = Join-Path $AddonFolder ("{0}.toc" -f $AddonFolder)
    }

    if ([string]::IsNullOrWhiteSpace($TocContentRoot)) {
        $TocContentRoot = Split-Path -Parent $TocPath
        if ([string]::IsNullOrWhiteSpace($TocContentRoot)) {
            $TocContentRoot = "."
        }
    }

    New-Item -ItemType Directory -Path $resolvedRepoRoot -Force | Out-Null
    New-Item -ItemType Directory -Path (Join-Path $resolvedRepoRoot $TocContentRoot) -Force | Out-Null
    New-Item -ItemType Directory -Path (Join-Path $resolvedRepoRoot "scripts") -Force | Out-Null

    $manifest = [ordered]@{
        schemaVersion         = 2
        toolchainVersion      = $script:AddonToolchainVersion
        addonId               = $AddonId
        displayName           = $DisplayName
        version               = $Version
        targetSupport         = $TargetSupport
        folders               = @($AddonFolder)
        minInstallerVersion   = "1.0.0"
        defaultWowPath        = $DefaultWowPath
        ptrWowPath            = $PtrWowPath
        tocPath               = $TocPath
        tocContentRoot        = $TocContentRoot
        releaseOutputDir      = "release-assets"
        publishTimeoutSeconds = 120
    }

    if (-not [string]::IsNullOrWhiteSpace($VersionFilePath)) {
        $manifest.versionFilePath = $VersionFilePath
    }

    if (-not [string]::IsNullOrWhiteSpace($CoverageScriptPath)) {
        $manifest.coverageScriptPath = $CoverageScriptPath
    }

    if ($CoverageArguments.Count -gt 0) {
        $manifest.coverageArguments = $CoverageArguments
    }

    Write-JsonFile -Path (Get-ProjectManifestPath -RepoRoot $resolvedRepoRoot) -Value $manifest

    $tocAbsolutePath = [System.IO.Path]::GetFullPath((Join-Path $resolvedRepoRoot $TocPath))
    if (-not (Test-Path -LiteralPath $tocAbsolutePath -PathType Leaf)) {
        $tocContent = @(
            "## Interface: 11507"
            "## Title: $DisplayName"
            "## Version: $Version"
            ""
        ) -join "`n"
        Set-Content -LiteralPath $tocAbsolutePath -Value $tocContent -Encoding utf8
    }

    Sync-AddonToolchain -RepoRoot $resolvedRepoRoot -SourceModulePath (Get-CurrentModulePath)
}

Export-ModuleMember -Function Get-AddonToolchainInfo, Resolve-AddonProject, Invoke-AddonAction, Invoke-AddonRelease, Test-AddonProject, Sync-AddonToolchain, New-AddonProject
