# Generated by AddonDevTooling. Do not edit manually.
param(
    [string]$OutputDir,

    [string]$ReleaseNotes = "",

    [string]$Version,

    [string]$ExpectedVersion,

    [switch]$PublishRelease,

    [int]$PublishTimeoutSeconds
)

$modulePath = Join-Path $PSScriptRoot "AddonDevTools.psm1"
if (-not (Test-Path -LiteralPath $modulePath -PathType Leaf)) {
    throw "AddonDevTools module was not found at '$modulePath'."
}

Import-Module $modulePath -Force

$invokeParams = @{
    RepoRoot     = (Split-Path -Parent $PSScriptRoot)
    ReleaseNotes = $ReleaseNotes
}

if ($PSBoundParameters.ContainsKey("OutputDir")) {
    $invokeParams.OutputDir = $OutputDir
}

if ($PSBoundParameters.ContainsKey("Version")) {
    $invokeParams.Version = $Version
}

if ($PSBoundParameters.ContainsKey("ExpectedVersion")) {
    $invokeParams.ExpectedVersion = $ExpectedVersion
}

if ($PublishRelease) {
    $invokeParams.PublishRelease = $true
}

if ($PSBoundParameters.ContainsKey("PublishTimeoutSeconds")) {
    $invokeParams.PublishTimeoutSeconds = $PublishTimeoutSeconds
}

Invoke-AddonRelease @invokeParams
