# Generated by AddonDevTooling. Do not edit manually.
param(
    [switch]$SkipPackaging
)

$modulePath = Join-Path $PSScriptRoot "AddonDevTools.psm1"
if (-not (Test-Path -LiteralPath $modulePath -PathType Leaf)) {
    throw "AddonDevTools module was not found at '$modulePath'."
}

Import-Module $modulePath -Force
Test-AddonProject -RepoRoot (Split-Path -Parent $PSScriptRoot) -IncludePackaging:(-not $SkipPackaging)
